service:
  name: oneil-farm-bot
  type: web
  env: node
  buildCommand: npm install
  startCommand: node bot_discord.js
  envVars:
    - key: DISCORD_TOKEN
      sync: false
    - key: MONGODB_URI
      sync: false
    - key: PORT
      value: 10000
    - key: CHANNEL_ID_FERMIERS
      sync: false
    - key: NODE_ENV
      value: production